# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
content-type: application/json

{
    "Name": "Alessandro"
}


###

# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
content-type: application/json

{
    "name": "mattia"
}

###

# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
content-type: application/json

{
    "name": "Frinco"
}

###

# SET name #
PUT http://localhost:3000/settings/user/533785d5-83b2-4cee-81c2-9be076780008/setusername HTTP/1.1
Authorization: 1
content-type: application/json

{
    "name": "Caminniti"
}

### 

# DELETE USER #
DELETE http://localhost:3000/settings/user/5766ef72-d865-4189-b4e4-53c2d2a4fa94  HTTP/1.1
Authorization: 5

### 

# SET PROFILE PHOTO #
PUT http://localhost:3000/settings/e2122bab-c201-4065-a929-ff47b819acc0/userphoto HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----BOUNDARY_STRING

------BOUNDARY_STRING
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------BOUNDARY_STRING--
###

# CREATE GROUP #
POST http://localhost:3000/chats/42839c6e-4a40-4514-bbf7-2ec24410e8f9/creategroup  HTTP/1.1
Authorization: 1
content-type: application/json

{
    "Name": "fate"
    

}

### 

# ADD TO GROUP #
PUT http://localhost:3000/chats/42839c6e-4a40-4514-bbf7-2ec24410e8f9/084864db-2d64-4adb-b576-21cd3c120c95/Agroup  HTTP/1.1
Authorization: 2
content-type: application/json 

 {
  "users": [
    {
      "userId": "1603d608-1534-43d3-b37b-a950979f4fe4",
      "username": "ciz",
      "photo": ""
    }
  ]
}


### 

# LEAVE GROUP #
DELETE http://localhost:3000/chats/544e8a18-f0df-4ada-b3b4-9968f80d14da/2d4289b4-e7ab-40e2-b316-bcb8bbbad9c7/leavegroup  HTTP/1.1
Authorization: 1

###

# SET GROUPNAME #
PUT http://localhost:3000/chats/eb11c7b3-bf21-42a1-9299-a52c33842c27/2d4289b4-e7ab-40e2-b316-bcb8bbbad9c7/Groupname HTTP/1.1
Authorization: 1
content-type: application/json

{
    "groupName": "eletti"
} 

### 

# SET GROUP PHOTO #
PUT http://localhost:3000/chats/9f7e39a2-ed8f-43c5-a8cd-2901f6967c33/03fa5509-3d98-441b-aac2-c83e91e0ea6e/Grouphoto  HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# CREATE CONVERSATION #

PUT http://localhost:3000/chats/e2122bab-c201-4065-a929-ff47b819acc0/CreatePrivateConversation/827a8653-4d6e-4b29-9f03-ff0b5f592f9d  HTTP/1.1
Authorization: 1


###



# GET CONVERSATIONS #
### GET chats with path param (se cambi il router)
GET http://localhost:3000/chats/e2122bab-c201-4065-a929-ff47b819acc0 HTTP/1.1
Authorization: 1

### 

# SEND MESSAGE #
POST http://localhost:3000/chats/e93646a8-59d3-436b-a487-22593d7127e8/4335f84a-2b08-4078-96f9-c1e1e6242de0/messages  HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

ciao
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# FORWARD MESSAGE #
POST http://localhost:3000/chats/ac0e7287-3cb3-417f-8a84-0c42f4181640/00839a7f-d4c1-494e-acfd-9eef4beec9f4/forward_messages/9762727c-cbab-4966-b9fb-59a2317ad0dc HTTP/1.1
Authorization: 1
content-type: application/json

{
    "messageId": "ca697ad4-90c0-419c-a061-898992f8e025"
}

###

# DELETE MESSAGE #
DELETE http://localhost:3000/chats/ac0e7287-3cb3-417f-8a84-0c42f4181640/c9aa4a94-98a3-4cc8-aa6c-3be0b50cadec/delete_message/98208fa7-e712-41f6-a4eb-cd1b300532af  HTTP/1.1
Authorization: 1

###

# GET CONVERSATION #
GET http://localhost:3000/chats/ab090ae4-744b-4d7e-8291-1fea7cfddeb0/752d7615-d3bb-479a-bc8d-0a8e780d5b2a  HTTP/1.1
Authorization: 1 

###

# COMMENT MESSAGE # 
POST http://localhost:3000/chats/ac0e7287-3cb3-417f-8a84-0c42f4181640/00839a7f-d4c1-494e-acfd-9eef4beec9f4/comment HTTP/1.1
Authorization: 1
content-type: application/json

{
    "messageId": "ca697ad4-90c0-419c-a061-898992f8e025",
    "comment": "😅"
}

### 

# UNCOMMENT MESSAGE #
DELETE http://localhost:3000/chats/ac0e7287-3cb3-417f-8a84-0c42f4181640/00839a7f-d4c1-494e-acfd-9eef4beec9f4/comment/4d237398-18dd-4e82-9897-8a17de946a48 HTTP/1.1
Authorization: 1
content-type: application/json
###

GET http://localhost:3000/session/getuser/e2122bab-c201-4065-a929-ff47b819acc0 HTTP/1.1
Authorization: 1
###
GET http://localhost:3000/users/search?name=Frinco HTTP/1.1
Authorization: 1